# the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
# version: '3.8'

services:
  web:
    build:
      context: .
    working_dir: /app/project
    command: bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0.0.0.0:8000 project.wsgi:application"
    image: wordlas
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:PostgresDevPassword@db:5432/wordlas
    volumes:
      - ./project:/app/project
      - ./project/main/static:/app/main/static

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: wordlas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: PostgresDevPassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
