# Generated by Django 5.1.3 on 2025-02-19 18:02

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(db_column='game_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word_to_guess', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuessResultPattern',
            fields=[
                ('id', models.AutoField(db_column='pattern_id', primary_key=True, serialize=False)),
                ('pattern', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('G', 'Green'), ('Y', 'Yellow'), ('N', 'None')], max_length=1), size=None)),
            ],
            options={
                'db_table': 'guess_patterns',
            },
        ),
        migrations.CreateModel(
            name='DictionaryWord',
            fields=[
                ('id', models.AutoField(db_column='word_id', primary_key=True, serialize=False)),
                ('word_text', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('complexity', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'dictionary_words',
                'indexes': [models.Index(fields=['word_text'], name='dictionary__word_te_704e5a_idx'), models.Index(fields=['complexity'], name='dictionary__complex_f67b3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Guess',
            fields=[
                ('id', models.UUIDField(db_column='guess_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guessed_word', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='api.game')),
                ('result_pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guesses', to='api.guessresultpattern')),
            ],
            options={
                'db_table': 'game_guesses',
                'ordering': ['attempt_number'],
                'unique_together': {('game', 'attempt_number')},
            },
        ),
    ]
