# Generated by Django 5.1.3 on 2025-02-20 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guessresultpattern',
            name='pattern',
        ),
        migrations.AlterField(
            model_name='game',
            name='word_to_guess',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
