# Generated by Django 5.1.6 on 2025-05-09 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_game_user_alter_game_word_to_guess_gamestatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="guessresultpattern",
            name="pattern",
            field=models.CharField(
                blank=True,
                choices=[("G", "Green"), ("Y", "Yellow"), ("N", "None")],
                default="NNNNN",
                max_length=5,
                null=True,
                validators=[django.core.validators.MinLengthValidator(5)],
            ),
        ),
    ]
