# Generated by Django 5.1.6 on 2025-05-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_guessresultpattern_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestatistics",
            name="last_game_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
