# Generated by Django 5.1.6 on 2025-05-09 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_gamestatistics_last_game_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamestatistics",
            name="last_game_id",
        ),
    ]
